// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtADbBX4jHChk5bJjnGJGTCqQH5axlJA',
    appId: '1:1056914919857:web:17a4b5a7ab9c8d9312ed90',
    messagingSenderId: '1056914919857',
    projectId: 'bonus-project-3da75',
    authDomain: 'bonus-project-3da75.firebaseapp.com',
    storageBucket: 'bonus-project-3da75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVgGHq-bKq1XErqvr6EY8oIN4YN40I9O0',
    appId: '1:1056914919857:android:c048f3334e07b54a12ed90',
    messagingSenderId: '1056914919857',
    projectId: 'bonus-project-3da75',
    storageBucket: 'bonus-project-3da75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyeLrDmsDochqHZH5kxSxsdZEiQpxrV60',
    appId: '1:1056914919857:ios:922fce9de69b9d3b12ed90',
    messagingSenderId: '1056914919857',
    projectId: 'bonus-project-3da75',
    storageBucket: 'bonus-project-3da75.firebasestorage.app',
    iosBundleId: 'com.example.simpleExpenseCalculator',
  );
}
